src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Deskripsi Tidak Boleh Kosong")
     * @Assert\Length(max=255, maxMessage="panjang input tidak lebih dari 255 karakter")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_done;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $done_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsDone(): ?bool
    {
        return $this->is_done;
    }

    public function setIsDone(?bool $is_done): self
    {
        $this->is_done = $is_done;

        return $this;
    }

    public function getDoneAt(): ?\DateTimeInterface
    {
        return $this->done_at;
    }

    public function setDoneAt(?\DateTimeInterface $done_at): self
    {
        $this->done_at = $done_at;

        return $this;
    }
}

src/Form/TodoType.php
<?php

namespace App\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TodoType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('description', TextType::class, [
            "required"=>false
        ])
        ->add("save", SubmitType::class);
    }

}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Repository\TodoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Todo;
use App\Form\TodoType;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


class TodoController extends AbstractController
{

    /**
     * @Route("/todo", name="todo")
     */
    public function index(TodoRepository $repository)
    {
        return $this->render('todo/index.html.twig', [
            'controller_name' => 'TodoController',
            "todos" => $repository->findAll()
        ]);
    }

    /**
     * @Route("/todo/{id}/done", name="todo_done", methods={"GET"})
     */
    public function done(Todo $todo)
    {
        // $todo = $repository->find($id);
        // if(!$todo)
        // {
        //     throw new NotFoundHttpException();
        // }
        $todo->setIsDone(true);
        $todo->setDoneAt(new \DateTime());
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($todo);
        $entityManager->flush();
        // redirect todo index
        return $this->redirectToRoute("todo");
    }

    /**
     * @Route("/todo/{id}/delete", name="todo_delete", methods={"GET"})
     */
    public function delete(string $id, TodoRepository $repository)
    {

    }

    /**
     * @Route("/todo/form/{id}", defaults={"id"=null}, name="todo_form", methods={"POST", "GET"})
     */
    public function form(?string $id=null, Request $request, TodoRepository $repository)
    {
        // pengecekan apakah id tidak null
        if($id){
            // mencari data berdasarkan id untuk edit data
            $todo = $repository->find($id);
        } else {
            // instansiasi Entity Todo
            $todo = new Todo();
        }

        if(!$todo){
            throw new NotFoundHttpException();
        }
        $form = $this->createForm(TodoType::class, $todo);
        $form->handleRequest($request);
        // mengecek apakah tombol submit ditekan dan juga melakukan validasi
        if($form->isSubmitted() && $form->isValid())
        {
            // menangkap data yg diinput dari form
            $todo = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($todo);
            $entityManager->flush();
            return $this->redirectToRoute("todo");
        }
        return $this->render("todo/create.html.twig", ["form"=>$form->createView()]);
    }

}

templates/base.html.twig
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block css %}{% endblock %}
    <title>
        {% block title %}Welcome{% endblock %}
    </title>
  </head>
  <body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/todo/create.html.twig
{% extends "base.html.twig" %}
{% block title %}Add Todo{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <h1>Form Todo List</h1>
        {{ form(form) }}
        {# <form method="POST" action="{{ path('todo_create') }}">
            <div class="form-group">
                <label for="description">
                    Description
                </label>
                <input type="text" class="form-control" name="description" id="description" autofocus autocomplete="off">
            </div>
            <button type="submit" name="submit" class="btn btn-primary btn-md">
                Simpan Todo
            </button>
        </form> #}
    </div>
</div>
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TodoController!{% endblock %}

{% block content %}
    <div class="row mt-5">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="text-center table-warning text-secondary">
                        <tr>
                            <th scope="col">
                                No
                            </th>
                            <th scope="col">
                                Todo
                            </th>
                            <th scope="col">
                                Status
                            </th>
                            <th scope="col">
                                Pilihan
                            </th>
                        </tr>
                    </thead>
                    <tbody class="">
                        {% for i, data in todos %}
                        <tr>
                            <td>
                                {{ i + 1 }}
                            </td>
                            <td>
                                {{ data.description }}
                            </td>
                            <td>
                                {% if data.isDone %}
                                    {{ "Selesai Pada:\t" ~ (data.doneAt | date("d-m-Y H:i:s")) }}
                                {% else %}
                                    {{ "Belum Selesai" }}
                                    <a href="{{ path('todo_done', {id: data.id}) }}" class="btn btn-success btn-sm float-right" id="btn-edit">
                                    Set Selesai
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                <div  class="d-flex justify-content-between">
                                    <a href="{{ path('todo_form', {id: data.id}) }}" class="btn btn-warning btn-sm  mr-2" id="btn-edit">
                                        Edit
                                    </a>
                                    <a href="{{ path('todo_delete', {id: data.id}) }}" class="btn btn-danger btn-sm" id="btn-delete">
                                        Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{{ path('todo_form') }}" class="btn btn-primary btn-md" id="btn-tambah">
                    Tambah Baru
                </a>
            </div>
        </div>
    </div>
{% endblock %}